export const START_TIMER = 'START_TIMER';
export const TICK = 'TICK';
export const SET_USER='SET_USER';
export const SET_RICHTEXT_LIST = 'SET_RICHTEXT_LIST';
export const SET_LINK_LIST = 'SET_LINK_LIST';
export const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST';
export const SET_BOOK_LIST = 'SET_BOOK_LIST';
export const SET_THEME_LIST = 'SET_THEME_LIST';
export const SET_DOCUMENT_DIMENSION = 'SET_DOCUMENT_DIMENSION';
export const SET_AUDIO_LIST = 'SET_AUDIO_LIST';

